# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'gr-lychee-opencv' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for gr-lychee-opencv
  pod 'Moscapsule', :git => 'https://github.com/flightonary/Moscapsule.git'
  pod 'OpenSSL-Universal', '~> 1.0.1.l'

  target 'gr-lychee-opencvTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'gr-lychee-opencvUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
